name: Daily NewRelic Cron Job

on:
  schedule:
    - cron: '30 1 * * *'  # Runs at 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:  # Allow manual trigger as well

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests google-cloud-bigquery python-dotenv psycopg2-binary

      - name: Decode and write Google credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > auth.json
          export GOOGLE_APPLICATION_CREDENTIALS=auth.json
        shell: bash

      - name: Run NewRelic data script
        env:
          NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
