name: Daily NewRelic Cron Job

on:
  schedule:
    - cron: '30 1 * * *'  # Runs at 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:  # Allow manual trigger as well

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests google-cloud-bigquery python-dotenv

      - name: Set up Google credentials
        run: |
          cat <<EOF > auth.json
          ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          EOF
          export GOOGLE_APPLICATION_CREDENTIALS=auth.json
        shell: bash

      - name: Run NewRelic data script
        env:
          NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
        run: python main.py
