name: Daily NewRelic Cron Job

on:
  schedule:
    - cron: '30 1 * * *'  # Runs at 7:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > auth.json
          export GOOGLE_APPLICATION_CREDENTIALS=auth.json

      - name: Run NewRelic data script
        env:
          NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
        run: python main.py
